version: "3.7"
services:
  client_dev:
    container_name: client_dev_agrimarket
    build:
      context: .
    restart: always
    hostname: client_dev_agrimarket
    ports:
      - "3010:3000"
    dns:
      - 8.8.8.8
      - 9.9.9.9
    volumes:
      - type: bind
        source: ./
        target: /app
